export const columns = {
  // LEDGER
  0: [
    {
      Header: "ID",
      accessor: "id" as const,
      type: "number",
      required: true,
      disabled: true,
    },
    {
      Header: "Created At",
      accessor: "created_at" as const,
      type: "datetime-local",
      required: false,
      disabled: true,
    },
    {
      Header: "Created By",
      accessor: "created_by" as const,
      type: "text",
      required: true,
      disabled: true,
    },
    {
      Header: "Responsible Person",
      accessor: "responsible_person" as const,
      type: "text",
      required: true,
      disabled: false,
    },
    {
      Header: "Responsible Person Phone",
      accessor: "responsible_person_phone" as const,
      type: "text",
      required: true,
      disabled: false,
    },
    {
      Header: "Company Type",
      accessor: "company_type" as const,
      type: "text",
      required: true,
      disabled: false,
    },
    {
      Header: "Work Address",
      accessor: "work_address" as const,
      type: "text",
      required: true,
      disabled: false,
    },
    {
      Header: "Home Address",
      accessor: "home_address" as const,
      type: "text",
      required: true,
      disabled: false,
    },
    { Header: "City", accessor: "city" as const, type: "text", required: true },
    {
      Header: "Pincode",
      accessor: "pincode" as const,
      type: "text",
      required: true,
      disabled: false,
    },

    {
      Header: "State",
      accessor: "state_" as const,
      type: "text",
      required: true,
      disabled: false,
    },
    {
      Header: "Country",
      accessor: "country" as const,
      type: "text",
      required: true,
      disabled: false,
    },
    {
      Header: "Marriage Anniversary",
      accessor: "anniversary" as const,
      type: "text",
      required: false,
      disabled: false,
    },
    {
      Header: "Company Phone",
      accessor: "company_phone" as const,
      type: "text",
      required: true,
      disabled: false,
    },
    {
      Header: "Company Email",
      accessor: "company_email" as const,
      type: "text",
      required: true,
      disabled: false,
    },
    {
      Header: "GSTIN",
      accessor: "gstin" as const,
      type: "text",
      required: true,
      disabled: false,
    },
    {
      Header: "DL No.",
      accessor: "drug_lisence" as const,
      type: "text",
      required: true,
      disabled: false,
    },
    { Header: "PAN", accessor: "pan" as const, type: "text", required: true },
    {
      Header: "Group",
      accessor: "group_" as const,
      type: "dropdown",
      required: true,
      disabled: false,
    },
    {
      Header: "Last Updated",
      accessor: "last_updated" as const,
      type: "datetime-local",
      required: false,
      disabled: true,
    },
    {
      Header: "Updated By",
      accessor: "updated_by" as const,
      type: "text",
      required: true,
      disabled: true,
    },
    {
      Header: "Comments",
      accessor: "comments_" as const,
      type: "text",
      required: true,
      disabled: false,
    },
  ],

  // Inventory
  1: [
    // { Header: "ID", accessor: "user_id" as const },
    // { Header: "Edited By", accessor: "edited_by" as const },
    { Header: "Name", accessor: "company_name" as const },
    { Header: "Email", accessor: "email" as const },
    { Header: "Contact", accessor: "contact" as const },
    { Header: "Address", accessor: "address" as const },
    { Header: "Pin", accessor: "pin" as const },
    { Header: "City", accessor: "city" as const },
    { Header: "States", accessor: "states" as const },
    { Header: "Country", accessor: "country" as const },
    { Header: "TypeOfCompany", accessor: "typeofcompany" as const },
    { Header: "DL NO", accessor: "dl_no" as const },
    { Header: "Pan No", accessor: "pan_no" as const },
    { Header: "Responsible Person", accessor: "responsible_person" as const },
    { Header: "Responsible Phone", accessor: "responsible_phone" as const },
    { Header: "GSTIN", accessor: "gstin" as const },
  ],
  // PAYMENTS
  2: [],
  // PURCHASE
  3: [
    { Header: "Last Updated", accessor: "last_updated" as const },
    { Header: "Party Name", accessor: "party_name" as const },
    { Header: "Party ID", accessor: "party_id" as const },
    { Header: "Invoice Number", accessor: "invoice_no" as const },
    { Header: "Due Date", accessor: "due_date" as const },
    { Header: "Date Created", accessor: "date_created" as const },
    { Header: "Amount", accessor: "amount" as const },
    { Header: "Status", accessor: "status" as const },
    { Header: "Transporter Name", accessor: "transporter_name" as const },
    { Header: "Transporter Cost", accessor: "transporter_cost" as const },
    { Header: "Edited By User", accessor: "edited_by_user" as const },
    { Header: "Comments", accessor: "comments_" as const },
  ],
  // SALES
  4: [
    { Header: "Last Updated", accessor: "last_updated" as const },
    { Header: "Party Name", accessor: "party_name" as const },
    { Header: "Party ID", accessor: "party_id" as const },
    { Header: "Invoice Number", accessor: "invoice_no" as const },
    { Header: "Due Date", accessor: "due_date" as const },
    { Header: "Date Created", accessor: "date_created" as const },
    { Header: "Amount", accessor: "amount" as const },
    { Header: "Status", accessor: "status" as const },
    { Header: "Transporter Name", accessor: "transporter_name" as const },
    { Header: "Transporter Cost", accessor: "transporter_cost" as const },
    { Header: "Edited By User", accessor: "edited_by_user" as const },
    { Header: "Comments", accessor: "comments_" as const },
  ],
};
